# Generated by Django 6.0.1 on 2026-02-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userpreferences_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
    ]
