# Generated by Django 6.0.1 on 2026-02-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userpreferences_dark_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="daily_summary",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="task_reminders",
        ),
    ]
